### ISSUE TITLE
powerbi.extensibility.utils is always undefined

### ISSUE THREAD

**Issue by denikqwerty** [microsoft/powerbi-visuals-bulletchart#32]
Good day.

Maybe this is stupid question, but I spent a low of time on this, and still didn`t resolve the issue.

I`m trying to make this sample work but when I downloaded it and used

`npm install -save`

After this I used

 `pbiviz start` .

When I try to run this, it doesn`t work. In console I`m always catching the same error:

> VM9635:24937 Uncaught TypeError: Cannot read property 'dataview' of undefined
    at <anonymous>:24937:69
    at <anonymous>:25013:11
    at <anonymous>:25014:7
    at Object.<anonymous> (<anonymous>:25015:3)
    at Object.<anonymous> (<anonymous>:26041:30)
    at __webpack_require__ (<anonymous>:35:30)
    at <anonymous>:99:18
    at Window.<anonymous> (<anonymous>:102:10)
    at <anonymous>:27655:20
    at Object.i [as injectJsCode] (VM9320 visualhostcore.min.js:2)

![image](https://user-images.githubusercontent.com/18682294/58694516-d64c3980-839b-11e9-9f3f-76d723084a57.png)

What can be a reason of this problem?

This is my pbiviz.json:

> {
  "visual": {
    "name": "BulletChart",
    "displayName": "Bullet Chart 1.8.1",
    "guid": "BulletChart1443347686880",
    "visualClassName": "BulletChart",
    "version": "1.8.1",
    "description": "A bullet chart that includes four orientations and a few customization options. Use to feature a single measure against a qualitative range.",
    "supportUrl": "https://community.powerbi.com",
    "gitHubUrl": "https://github.com/Microsoft/powerbi-visuals-bulletchart"
  },
  "apiVersion": "1.13.0",
  "author": {
    "name": "Microsoft",
    "email": "pbicvsupport@microsoft.com"
  },
  "assets": {
    "icon": "assets/icon.png"
  },
  "externalJS": [
    "node_modules/lodash/lodash.min.js",
    "node_modules/d3/d3.js",
    "node_modules/powerbi-visuals-utils-typeutils/lib/index.js",
    "node_modules/moment/min/moment.min.js",
    "node_modules/globalize/lib/globalize.js",
    "node_modules/globalize/lib/cultures/globalize.culture.en-US.js",
    "node_modules/powerbi-visuals-utils-svgutils/lib/index.js",
    "node_modules/powerbi-visuals-utils-dataviewutils/lib/index.js",
    "node_modules/powerbi-visuals-utils-formattingutils/lib/index.js",
    "node_modules/powerbi-visuals-utils-interactivityutils/lib/index.js",
    "node_modules/powerbi-visuals-utils-chartutils/lib/index.js",
    "node_modules/powerbi-visuals-utils-colorutils/lib/index.js",
    "node_modules/powerbi-visuals-utils-tooltiputils/lib/index.js"
  ],
  "style": "style/bulletChart.less",
  "capabilities": "capabilities.json"
}

And tsconfig.json:

> {
  "compilerOptions": {
    "allowJs": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "ES5",
    "sourceMap": true,
    "out": "./.tmp/build/visual.js",
    "declaration": true
  },
  "files": [
    ".api/v1.13.0/PowerBI-visuals.d.ts",
    "node_modules/powerbi-visuals-utils-typeutils/lib/index.d.ts",
    "node_modules/powerbi-visuals-utils-dataviewutils/lib/index.d.ts",
    "node_modules/powerbi-visuals-utils-formattingutils/lib/index.d.ts",
    "node_modules/powerbi-visuals-utils-interactivityutils/lib/index.d.ts",
    "node_modules/powerbi-visuals-utils-svgutils/lib/index.d.ts",
    "node_modules/powerbi-visuals-utils-chartutils/lib/index.d.ts",
    "node_modules/powerbi-visuals-utils-colorutils/lib/index.d.ts",
    "node_modules/powerbi-visuals-utils-tooltiputils/lib/index.d.ts",
    "node_modules/powerbi-models/dist/models-noexports.d.ts",
    "src/dataInterfaces.ts",
    "src/settings.ts",
    "src/columns.ts",
    "src/visualLayout.ts",
    "src/visual.ts"
  ]
}

Thank you in advance!

**Comment by helen508light** [comment]
Hi @denikqwerty 
Which version( commit hash or branch) do you use?
Did you changed the source code?
If you hadn't changed anything the problem may be caused by mismatch of powerbi-visual-tools you had installed globally and tools version used in the visual.
I seems like u had 3.x.x tools globally, but 1.3 locally in the visual code

use "npm run start" instead of "pbiviz start"
